version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
